name: tuttorial-iceflow
channels:
- conda-forge
dependencies:
- python=3.8
- bqplot~=0.12.21
- cartopy~=0.18.0
- geopandas~=0.8.1
- h5py~=3.1.0
- ipyleaflet~=0.13.6
- ipympl~=0.6.3
- ipywidgets~=7.6.3
- joblib~=0.16.0
- jupyterlab~=3.0.6
- matplotlib-base~=3.3.4
- nbgitpuller~=0.9.0
- requests~=2.25.1
- sidecar~=0.5.0
- tqdm~=4.56.0
- vaex~=3.0.0
- xarray~=0.16.2
- pip
- pip:
  - icepyx
  - git+git://github.com/nsidc/python-cmr
