name: itslive-notebooks
channels:
- conda-forge
dependencies:
- python=3.8
- matplotlib-base>=3.2.1
- dask=2.30.0
- ipyleaflet=0.13.6
- pandas=1.2.2
- cartopy=0.17.0
- geopandas=0.8.1
- joblib=0.13.2
- h5py=2.10.0
- requests=2.22.0
- xarray=0.16.2
- pyresample=1.13.2
- netcdf4=1.5.6
- zarr=2.6.1
- descartes=1.1.0
- jupyterlab=3
- ipympl=0.6.3
- sidecar=0.5.0
- tqdm
- nbgitpuller
- s3fs
- flake8
- jupyter-offlinenotebook
- pip
- pip:
  - icepyx
  - python-cmr
